# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170612_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
