# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170524_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='report_frequency',
            field=models.CharField(default='monthly', max_length=10),
        ),
    ]
