# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 13:14
from __future__ import unicode_literals
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170524_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='next_report_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now()),
        ),
    ]
