# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170525_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='next_report_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
