# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170525_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='report_frequency',
        ),
    ]
