# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_profile_report_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='report_frequency',
            field=models.CharField(default='monthly', max_length=10),
        ),
    ]
