# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-05 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_report_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecksScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_code', models.UUIDField()),
                ('user', models.CharField(max_length=30)),
                ('pause_check', models.BooleanField(default=False)),
                ('see_logs', models.BooleanField(default=False)),
                ('remove_check', models.BooleanField(default=False)),
            ],
        ),
    ]
