# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-05 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_checksscope'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChecksScope',
            new_name='CheckScope',
        ),
    ]
