# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20170526_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='last_nag',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='nag',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='next_nag',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
