# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 07:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20170529_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='nag',
            field=models.DurationField(default=datetime.timedelta(0, 3600), null=True),
        ),
    ]
